### ISSUE TITLE
Makefile gcc6 for MAC

### ISSUE THREAD

**Issue by JE-Jimenez** [mrirecon/bart#113]
the Makefile need to be set to gcc6 to match the instruction in the "README" file. 
ifeq ($(BUILDTYPE), MacOSX)
	CC ?= gcc-mp-6

**Comment by jtamir** [comment]
You are right. In the meantime, you can make a `Makefile.local` file with the line `CC=gcc-mp06`

**Comment by JE-Jimenez** [comment]
I also notice that when you do type: _$ make install_ macOS won't allow you to save in /usr/bin, therefor it would be convenient if you add a option for Mac in the Makefile: e.g.
```
ifeq ($(BUILDTYPE), MacOSX)
         PREFIX ?= usr/local	
else
	PREFIX ?= usr/
endif
```
As you pointed out, I fixed this issue within the Makefile.local. if you install using brew then you don't need to worry about it. Well, I hope this comments are helpful. Thank very much for maintaining this AMAZING library.
