### ISSUE TITLE
Compilation error on RHEL7

### ISSUE THREAD

**Issue by brianhannamn** [mrirecon/bart#121]
I believe I have all the prerequisite libraries and gcc 4.8.5. Many parts do compile, but I reach this error on __auto_type and I'm unsure what is needed. Please advise. Thanks much, Brian Hanna CMRR

In file included from /opt/local/mrirecon/bart/src/num/ops.h:11:0,
                 from /opt/local/mrirecon/bart/src/linops/linop.c:18:
/opt/local/mrirecon/bart/src/linops/linop.c: In function ‘plus_apply’:
/opt/local/mrirecon/bart/src/misc/types.h:44:14: error: unknown type name ‘__auto_type’
 #define auto __auto_type
              ^

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)

**Comment by uecker** [comment]
Thank you. I think nowadays we need at least gcc 4.9. I will add this to the documentation.

**Comment by uecker** [comment]
minimum gcc version is now documented to be 5.0
