### ISSUE TITLE
pics total variation algorithm switch

### ISSUE THREAD

**Issue by jtamir** [mrirecon/bart#127]
It should be possible to select different iterative algorithms for total variation (currently: chambolle pock or ADMM) instead of always setting it to ADMM. We should move the hard-code ADMM in optreg.c to an assertion check in pics.c

**Comment by uecker** [comment]
We should probably have a generic switch to choose the algorithm and if none is specifically selected we should fall back to a sensible default. Then we should add assertions for impossible configurations.

**Comment by uecker** [comment]
So I moved the logic into its own function and file. It should now also not change any user specified choice and only select an algorithm automatically if none is selected. Needs testing...

**Comment by uecker** [comment]
Now, primal dual does not work because of nr_penalties == 2 constraint.... still closing.
