### ISSUE TITLE
Conflict with ox-bart

### ISSUE THREAD

**Issue by curtcorum** [mrirecon/bart#132]
Looks like the noreturn also breaks ox-bart...

Please see:
https://github.com/mrirecon/bart/commit/fbc2e46497d3fb1eb910e054d82b54e65bc4748d#comments

**Comment by jtamir** [comment]
You are correct. I don't have a workaround for this, except that I remove the "noreturn" whenever I recompile ox-bart...

@uecker do you have a better suggestion?

**Comment by curtcorum** [comment]
Jon,
I do not, since that is what I did! :)
Not sure why the nonreturn is needed in bart, it seems to break cuda as
well?
I have had initial luck using ox-bart with orchestra-sdk 1.7, but still
testing.
thanks!
Curt

**Comment by uecker** [comment]
Could you try to wrap this like this:
#ifndef __cplusplus
#endif
