### ISSUE TITLE
Segfault in cdf97

### ISSUE THREAD

**Issue by hcmh** [mrirecon/bart#142]
Hey,

starting from commit 3c1c2eb7cc3aaac92c6617d10d375ec630d9cc42 and including current master, the following code segfaults for me:

```
bart phantom -x 256 p
bart cdf97 3 p pw
```

Strangely enough, it does not segfault for `126`, `127`, or `128`, although the result is the original phantom instead of its wavelet decomposition:

`x=128`:
![128](https://user-images.githubusercontent.com/603787/43727803-49161be0-99a3-11e8-8fc3-79b83f297e21.png)

Previous commits do now show this problem.

**Comment by uecker** [comment]
Fixed.
