### ISSUE TITLE
Creating a BART GitHub Wiki

### ISSUE THREAD

**Issue by Takishima** [mrirecon/bart#154]
Would there be interests for creating GitHub Wiki pages for BART ?

I know that BART comes bundled with some documentation, but making that available directly from the GitHub repository might be more convenient for users looking to troubleshoot common problems.

As an example, I have written a small page on building `pyBART` after a question I got from @jtamir ([pyBART wiki](https://github.com/Takishima/bart/wiki/pyBART)). If there is interest, I could expand that to include a detailed description of the CMake build system (I personally don't use the Makefile...). This could be a good addition to the existing website but more focused towards building BART.

**Comment by uecker** [comment]
Well, in principle yes. But I will be able to move BART a way from Github at some point... so everything which could lock me into the Github platform is a no go.   All the issues stuff already starts to annoy me...

**Comment by Takishima** [comment]
Actually, the content of all GitHub wikis are easily downloadable since they are themselves also Git repositories. Additionally, they are nothing more than text files in Mardown format (or similar), so you should be able to very easily port them to other platforms.

Anyway, I will slowly develop the wiki on my fork of BART (covering the areas that I know well enough). Feel free to add parts of it to the official BART project  if you feel that it is worth it.
