### ISSUE TITLE
operator_p_(co)domain do not work correctly

### ISSUE THREAD

**Issue by hcmh** [mrirecon/bart#162]
`operator_p_domain()` and `operator_p_codomain()` contain the following code:
`assert(1u == op->op.io_flags);`
(see https://github.com/mrirecon/bart/blob/master/src/num/ops.c#L304)

However, in `operator_p_create2()`, we initialize this as:
`o->op.io_flags = MD_BIT(1);`
which is 2 (https://github.com/mrirecon/bart/blob/master/src/num/ops.c#L383). Therefore, `operator_p_domain()` can never work on any `operator_p_s` created by that function (which are all or almost all of them). 

This is obviously not working as intended. Should the assert check for 2 instead? In general, I don't really see what that check is there for...

**Comment by uecker** [comment]
should be fixed now.
