### ISSUE TITLE
fmemopen missing on Mac

### ISSUE THREAD

**Issue by jtamir** [mrirecon/bart#167]
fmemopen does not exist on BSD/OS X. Possible workaround is to include the following:
https://github.com/NimbusKit/memorymapping

**Comment by uecker** [comment]
Yes, also I am not sure about the license.

**Comment by jtamir** [comment]
Isn't it similar to BSD? The notable difference I see is the following:

   - A limitation of this license for developers is that it requires you to
   add prominent notifications of any changes you make to a file.

https://snyk.io/blog/mit-apache-bsd-fairest-of-them-all
Jon
---
jtsense.com

**Comment by uecker** [comment]
I am worried about the patents. BSD ignores patents Apache 2.0 does not. This could be a problem.
