### ISSUE TITLE
Residual convergence graph - intuition

### ISSUE THREAD

**Issue by johannestoger** [mrirecon/bart#170]
Hi, I'm adding this as an issue here because I'm not sure where to discuss these things. Please let me know if there is a better place.

In any case, I've been working on a golden angle radial real-time flow sequence with a temporal TV constraint. I started thinking about convergence, so I made a few plots of the convergence measures that the ADMM optimization outputs (rnorm and snorm). One example can be found in the link below.

https://imgur.com/1sQ8XPl

The left plot shows the convergence measures as a function of the total number of CG iterations performed (i.e. what you specify with the -i option), up to 1000 iterations. The lambda value is set to something that gives the best results I could get so far. The rho factor is dynamic, but I set it close to what it usually converges to for my problem, and it settles within the fest few iterations.

I can see some different "phases" here:

1. A rapid decay phase (0-100 or so)
1. A slower decay phase (100-400)
1. A "chaotic" phase (400-850)
1. A sharp drop (~850)
1. Very slow decay (850-1000)

So my question is this - is there some kind of intuition or knowledge to be gained from this? Can we explain the different phases? Can we use that knowledge to improve the optimization? Is it ADMM-specific, MRI-specific, or is it due to the combination of the two?

It might also be completely meaningless, but I thought I should at least show it.

Cheers,

Johannes

**Comment by uecker** [comment]
The right place for discussing this is the mailing list. On Github only few people will see it and everything will get lost if we move somewhere else.

**Comment by johannestoger** [comment]
OK, I'll move it there.
