### ISSUE TITLE
thread safety problem

### ISSUE THREAD

**Issue by davied9** [mrirecon/bart#174]
if fft_apply is called multi times in different thread, a `segmentation falut` will occur

```
fft_apply exit critical
fft_apply exit critical
fft_apply exit critical
fft_apply enter critical
fft_apply enter critical
fftw: alloc.c:187: assertion failed: (stat->cnt == 0 && stat->siz == 0) || (stat->cnt > 0 && stat->siz > 0)
Aborted (core dumped)
```

but according to [FFTW](http://www.fftw.org/doc/Usage-of-Multi_002dthreaded-FFTW.html), the execute interface should be thread safe

have any ideas about it? Thanks.

**Comment by davied9** [comment]
yes, this is locally built FFTW, with
```
COMMON="$COMMON --enable-debug"
COMMON="$COMMON --enable-type-prefix --prefix=$TARGETDIR --with-gcc --disable-fortran --enable-i386-hacks --enable-shared=yes --enable-threads"

make clean

./configure $COMMON --enable-sse2
make
make install
make clean

./configure $COMMON --enable-sse2 --enable-float
make
make install
make clean

./configure $COMMON --enable-long-double
make
make install
make clean
```

`--enable-threads` is given, which should solve thread safety problem according to  [FFTW](http://www.fftw.org/doc/Usage-of-Multi_002dthreaded-FFTW.html)

**Comment by uecker** [comment]
Maybe removing the "--enable-debug" option helps.
See here:
https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/270074

I am closing this issue as this seems unrelated to BART. If you think otherwise, please reopen
