### ISSUE TITLE
fPIC flag missing in CMakeLists.txt

### ISSUE THREAD

**Issue by pehses** [mrirecon/bart#177]
The standard Makefile includes the -fPIC compiler flag, so that bart can be used as an external library (e.g. in gadgetron). However, this flag is missing in CMakeLists.txt. Possible solution: Append the following lines somewhere after set(_compile_flags_c/cxx):

list(APPEND _compile_flags_c "-fPIC")
list(APPEND _compile_flags_cxx "-fPIC")

**Comment by uecker** [comment]
Thank you Philipp!  

@Takishima 
could we add this to CMakeLists.txt ?  
(Also it broke on master when I added tests/smallfov.mk)

**Comment by Takishima** [comment]
This is already implemented and supported by the current CMake: simply set the `BART_FPIC` option to `ON`.

E.g.   `cmake .. -DBART_FPIC=ON`

**Comment by Takishima** [comment]
@uecker I will have a look at the failures when I have more time next week.

**Comment by uecker** [comment]
Closing, as we do not currently have CMake anymore...
