### ISSUE TITLE
Error: "shared clf" using twixread

### ISSUE THREAD

**Issue by inhuszar** [mrirecon/bart#186]
Command:
bart twixread -A meas_MID00165_FID19032_mfc_3dflash_T1w_GRAPPA4_11mm.dat t1w_data

Output:
VD Header. MeasID: 143 FileID: 19010 Scans: 2
VD Header. MeasID: 143 FileID: 19010 Scans: 2
ERROR: shared cfl t1w_data.cfl

The error is returned immediately with the second line of output. The input file is a 3D gradient-echo image with GRAPPA 2x2 acceleration, 40x40 oversampling, 32 channels and 9 echoes. According to mapVBVD, the full shape of the data is: [416 32 182 159 1 1 1 9 1 1 1 1 1 1 1 1].

Possible reason:
I suspect that twixreader cannot handle the two scans in the TWIX file, one of which is a reference scan.

Any help would be greatly appreciated.

**Comment by uecker** [comment]
Yes, you are right. twixread currently cannot do this. You can export data selecting the 'single raidfile' option. I hope I can remove this limitation at some point in time...

**Comment by uecker** [comment]
This should work now. Please try again.

**Comment by mckib2** [comment]
@uecker  I am running into an error when reading starVIBE data with the same `ERROR: shared cfl` reported.  Is this the same issue as above?
