### ISSUE TITLE
Can bart support for non-parallel MRI reconstruction?

### ISSUE THREAD

**Issue by duancaohui** [mrirecon/bart#189]
There are many examples for parallel imaging and compressed sensing by using bart, can bart support for non-parallel MRI data, just single coil MRI data? These data don't have coil sensitivity map, thus it would cause errors.

Thanks!

**Comment by uecker** [comment]
Please use the mailing list for questions. This question has been answered before:
https://lists.eecs.berkeley.edu/sympa/arc/mrirecon/2017-08/msg00001.html
