### ISSUE TITLE
Missing 'end' in /bart/matlab/bart.m @ branch v0.4.04

### ISSUE THREAD

**Issue by MaxHausmann** [mrirecon/bart#194]
Hey,

just downloaded the last update (v0.4.04) and there is a missing 'end' in /bart/matlab/bart.m at line 33. 

Not existing in master branch, but I did use the link of the gh-page to download and than got to this version.

Best regards
Max

**Comment by uecker** [comment]
This should be fixed in the new version. Thank you.
