### ISSUE TITLE
undefined reference to problem when gcc nufft.c file

### ISSUE THREAD

**Issue by DBermudez0** [mrirecon/bart#203]
I have been trying to execute the nufft.c file located in the bart/src directory. However, when I compile the nufft.c file by running gcc nufft.c it gives me a lot of undefined reference to problems. How do I solve this issue.

**Comment by sidward** [comment]
Please simply run "make" in the bart directory.

**Comment by DBermudez0** [comment]
Yes, I already tried to run make in the bart directory and when I gcc nufft.c it still gives me the undefined reference to problem.

**Comment by jtamir** [comment]
If you were able to run make without problems, then you can call nufft
through the command line, "./bart nufft"
If you want a standalone binary for nufft, you can run "make nufft" from
the bart directory. Then you can call it directly with "./nufft". Note this
is true for any of the tools.

Jon
---
jtsense.com

**Comment by DBermudez0** [comment]
Okay. Can you give me a example that uses the nufft in bart. I looked at the examples that uses bart from python. However, non of those examples use the nufft.

**Comment by uecker** [comment]
Ok, here is a minimal example:
# create radial trajectory with 55 spokes
$ bart traj -x256 -y55 -r t
# divide by two for oversampling
$ bart scale 0.5 t t2
# simulate non-Cartesian k-space dta
$ bart phantom -k -t t2 k
# apply inverse nuFFT to reconstruct an image
$ bart nufft -i -t t2 k x

Please use the mailing list for further discussions. This is not a BART issue. Thank you.
