### ISSUE TITLE
Include density compensation and coil sensitivity maps as parameters for nufft?

### ISSUE THREAD

**Issue by DBermudez0** [mrirecon/bart#204]
Hi,

Is there a way to density compensation and coil sensitivity maps along with the k-space trajectory as extra parameters for the bart nufft?

**Comment by uecker** [comment]
Please use the mailing list.

**Comment by meysamtavakoli** [comment]
Hello,
I have a question regarding NUFFT reconstruction algorithm. I am not following what is the role of "coil sensitivity maps" ?

Thank you
