### ISSUE TITLE
NLINV with oversampled grid

### ISSUE THREAD

**Issue by MartinK84** [mrirecon/bart#220]
For some applications, I'm acquiring data with 2D and/or 3D radial sampling using a very narrow field of view (due to various reasons). The NUFFT implemented within BART has an option to reconstruct the images by keeping the 2x oversampled grid,
```
-1		use/return oversampled grid
```
The NLINV algorithm currently is missing this (even though surprisingly the coil maps returned do include the 2-times oversampled grid). 

I have tried to implement a parameter into the NLINV code to allow for the images to be returned using the 2x oversampled grid, which is so far quite straight forward:
https://github.com/MartinK84/bart/commit/0aa6a4dc98282971a78b3a03c127b146828cb0f3

When looking at the results this appears to work quite well for the NLINV reconstructed images:
![reco](https://user-images.githubusercontent.com/50527612/83620657-e9d14800-a58d-11ea-98cd-3de324234e7d.png)

However, the sensitivity maps appear to be influenced by this in the oversampled areas of the FoV:
![sens](https://user-images.githubusercontent.com/50527612/83620665-ec33a200-a58d-11ea-939d-555bed291196.png)

The differences in the sensitivity maps are only outside of the object and can easily be removed by using a magnitude threshold. I would like to nevertheless ask if there is a better way to implement this and if this behavior is something that would be expected when reconstructing NLINV with an oversampled grid? Finally, I would very much like to see this option to be included for the NLINV algorithm in some way or another, if my changes proposed above are sufficient feel free to incorporate them, I can also create a pull request if desired.

**Comment by uecker** [comment]
We can include it, but mathematically is a bit strange as one needs internal oversampling by 2 with everything outside the real FOV being masked so that everything is mathematically correct. So I wonder whether just scaling the trajectory so that the complete object is inside the FOV is not better?

**Comment by MartinK84** [comment]
Thank you for the explanation. You are correct, just scaling the trajectory by a factor of two has the same effect. I was not thinking about that. With the scaled trajectory NLINV returns the oversampled grid/FoV and also the coil maps appear to be clean of artifacts. This is the better solution than integrating a parameter that has the potential to breaks things internally (from a mathematical point of view). Thank you!

**Comment by uecker** [comment]
Good. It is usually advisable to have at least a bit oversampling left, e.g. not scale by 2 but 1.5 if the acquisition used a nominal oversampling of 2. Of course, the object should then not be much larger than the FOV selected of for the acquisition.
