### ISSUE TITLE
MATLAB Wrapper Unit Test

### ISSUE THREAD

**Issue by MartinK84** [mrirecon/bart#221]
During the recent BART Workshop one of the polls did show that apparently a majority of users are using BART in combination with the MATLAB wrapper. However, as far as I can see it there is no Unit Test available for the MATLAB wrapper to tests its functionality. 

MATLAB does include its own unit testing Fraemwork (see https://www.mathworks.com/help/matlab/matlab-unit-test-framework.html) and I wonder if there would be enough interest for a small Unit Test of the BART MATLAB wrapper to be developed. 

The idea would be to have a matlabTest.m/bartTest.m function in bart/tests (or bart/matlab?) that runs a basic unit test on the MATLAB wrapper. Useful things to test could be:
- Toolbox path set and finding of the bart binary
- Execution of the bart binary
- BART help from within MATLAB (see https://github.com/mrirecon/bart/pull/219)
- Runing bart with:
  - single and multiple input variables
  - no, single and multiple output variables

MATLAB Unit Tests are not trivial, but I have used the MATLAB Unit Testing Framework before and would be willing to contribute.

**Comment by uecker** [comment]
A test for the wrapper would certainly helpful! A simple test which can be run using octave would be ideal as we could run it as part of continuous integration testing. (I do not have Matlab in my lab)

**Comment by MartinK84** [comment]
I will see if I can find some time next week or so to give this a go. I will also check out the unit testing framework of Octave to see if it's to some extent compatible to MATLAB. If not manual try/catch and error checking with fprintf to the command window will have to do, and will also be better than no testing at all :-)

**Comment by jtamir** [comment]
What about a system test in the `tests` dir that calls an octave script to load a cfl, do some operation to it, then write a cfl, and use the `nrmse` tool as the final check? This would be similar to the other system tests.

**Comment by MartinK84** [comment]
> What about a system test in the `tests` dir that calls an octave script to load a cfl, do some operation to it, then write a cfl, and use the `nrmse` tool as the final check? This would be similar to the other system tests.

One could run a MATLAB/Octave script from the command line that runs an entire BART pipeline, read cfl, further process using BART Wrapper calls, write cfl, and then compare to the same data processed purely using BART from the shell. But the result would in general be always identical between BART from the shell and BART from MATLAB/Octave unless there is any error in the wrappers (because any MATLAB/Octave wrapper error will crash the entire pipeline/test). 

The question, in general, would be if the MATLAB/Octave unit test is more aimed at the developers, users, or both. From a developer point of view, the MATLAB/Octave wrappers are not really changed/updated that often and basically no changes in BART would influence them (unless there are major changes that completely change how BART works, e.g. cfl file format or how command-line parameters are passed), so the unit test would be sufficient to be a sanity check only for the MATLAB/Octave wrapper and no other part of BART. From a user point of view it would be great to have a simple script, e.g. test_bart.m, that a user could run from their current MATLAB/Octave session to quickly test if their local MATLAB/Octave setup works with BART (e.g. environmental variable set, write access to temp folder, bart help, bart calls with multiple parameters, etc.). The same script could also be used by the developers to test the Wrappers whenever changes to it are made (once a year or so).

Because the MATLAB/Octave wrappers are just a small addon for using BART I would suggest to go with the latter, more simple, solution of just using a self-contained MATLAB/Octave test script like test_bart.m that directly tests all MATLAB/Octave wrapper functionality and that can be easily run by the user and any developer who changes the wrappers on-demand.

**Comment by jtamir** [comment]
sounds good!

**Comment by uecker** [comment]
There is already a test for python export/import you can look at.

**Comment by MartinK84** [comment]
I have been taking a look at the python unit test in the tests folder, trying to get it to work as a start and trying to understand the integrated test system (and also use it as a blueprint for a possible MATLAB/OCTAVE test).  It's basically just a bunch of make files that export test make targets that are collected in TESTS, TESTS_GPU and TESTS_PYTHON and the targets run some commands and compare the result with nrmse?

I was able to run the python test with ```make tests/test-python-cfl```, however on my system ```make pythontest```, which is defined in the MakeFile, just returns with no rule to make target (presumably because ${TESTS_PYTHON} is not populated properly)? Is there anything that I have to do/setup to make "make pythontest" work?

On a side node: is it normal that ```make test``` takes ages? On my laptop it appears to be stuck with 100% CPU usage on the first ecalib unit test (I did manually abort after 30 minutes).

**Comment by uecker** [comment]
1) Yes, the tests are just makefile rules listed in these variables. They can do whatever you want. 
2) I fixed the python problem. 
3) Running all tests takes about 3 minutes on my desktop. If it is stuck somewhere, this is a bug. Sounds like a problem in your compiler.

**Comment by MartinK84** [comment]
I tried to look more into the Makefile system, but since I'm absolutely no expert in bash/shell scripting and Makefiles I gave up after spending hours on just trying to clone the python test to a matlab test and get anything to work. Adding anything to the Makefile tests is just beyond my skills, sorry.

But I did also go back to the original idea of having a test that is integrated into MATLAB/Octave. I have created a small test_bart.m script which you can find here: https://github.com/MartinK84/bart/blob/67eae8cba6a2498259e7009a14b6a9f78933d879/matlab/test_bart.m

This script is basically a super-simplified unit test system that works under MATLAB and Octave (The UT systems integrated in MATLAB and Octave are sadly completely different so I had to come up with something customized).

The script simply performs some BART commands using the MATLAB wrapper and checks if the commands did run without error, if data was returned and if the returned data is not empty. Basically only testing if the BART wrapper works.

test_bart.m works under MATLAB and Octave, the latter produces some more console output because the eval commands work different between MATLAB and Octave - but the performed tests are the same. When running from MATLAB the output is:

```matlab
>> test_bart
TEST [Environmental variable (TOOLBOX_PATH)] >> Passed
TEST [Write cfl file] - running "writecfl(file, data)" >> Passed
TEST [Read cfl file] - running "readcfl(file)" >> Passed
TEST [Data consistency cfl file] >> Passed
TEST [Wrapper (without parameter)] - running "bart" >> Passed
TEST [Wrapper (method help)] - running "bart traj -h" >> Passed
TEST [Wrapper (No input, no parameter)] - running "bart('phantom')" >> Passed
TEST [Wrapper (No input, no parameter) - check output] >> Passed
TEST [Wrapper (No input)] - running "bart('phantom -3')" >> Passed
TEST [Wrapper (No input) - check output)] >> Passed
TEST [Wrapper (One input, one parameter)] - running "bart('fft -u 3', varargin{1})" >> Passed
TEST [Wrapper (One input, one parameter) - check output)] >> Passed

TEST Result: All Tests Passed!
```

Although not integrated into the BART test system this could nevertheless be something that any user can just run themselves after starting MATLAB/Octave to test if their BART setup works.

If you think that this is something useful I can create a pull request.

**Comment by uecker** [comment]
I think it would be useful....

**Comment by MartinK84** [comment]
Added with 1512f4dcdded0b09cfd4acff4647c25cb697653b
