### ISSUE TITLE
Different behaviour between RTNLINV and NLINV with oversampled grid/image

### ISSUE THREAD

**Issue by MartinK84** [mrirecon/bart#222]
I have been using the NLINV algorithm for the reconstruction of some 2D radial data (thank you for that, it has been working great!). Because I'm sometimes (for various reasons) measure with a very tight field of view) it has been pointed out (here https://github.com/mrirecon/bart/issues/220) that I can also reconstruct the image with the oversampled grid/FOV by simply scaling my trajectory. This also has been working great with the NLINV algorithm.

When using the RTNLINV version (since I also have acquired frames/repetitions with the data) with the exact same inputs and parameters as the NLINV it in principle worked and did also return images with the same size as NLINV and including the oversampled grid/FOV as the NLINV version. However, the data is masked to the original/reduced FOV without oversampling:

![NLINVvsRTNLINV](https://user-images.githubusercontent.com/50527612/84284579-ad2cc000-ab3c-11ea-86a9-9acc073f3c3e.png)

Surprisingly, the coil sensitivities returned by RTNLINV do only have half the size of those returned by NLINV.  Judging from the debug output below I would guess that the psf dims would require twice the size to be coherent with NLINV. Is this difference between NLINV and RTNLINV intentional, a mistake, or just something that has not been added yet?

``` matlab
>> [recoNLINV, coilsensNLINV] = bart('nlinv -d4 -i14 -t', trajFile, data.vol);
nufft kernel dims: [  1  96 120   1   1   1   1   1   1   1  20   1   1   1   1   1   1 ]
nufft psf dims:    [350 350   1   1   1   1   1   1   1   1  20   1   1   1   1   1   1 ]
nufft traj dims:   [  3  96 120   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
Allocating 230400 (vs. 2680400) + 2450000
ksp : [  1  96 120   1   1   1   1   1   1   1  20   1   1   1   1   1   1 ]
cim : [350 350   1   1   1   1   1   1   1   1  20   1   1   1   1   1   1 ]
traj: [  3  96 120   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
ksp : [  1  96 120   8   1   1   1   1   1   1  20   1   1   1   1   1 ]
cim : [350 350   1   8   1   1   1   1   1   1  20   1   1   1   1   1 ]
traj: [  3  96 120   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
Scaling: 8.542377

>> [recoNLINVRT, coilsensNLINVRT] = bart('rtnlinv -d4 -i14 -t', trajFile, data.vol);
[  0   0   0 ]
nufft kernel dims: [  1  96 120   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
nufft psf dims:    [175 175   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
nufft traj dims:   [  3  96 120   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
Allocating 11520 (vs. 42145) + 30625
ksp : [  1  96 120   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
cim : [175 175   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
traj: [  3  96 120   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
ksp : [  1  96 120   8   1   1   1   1   1   1   1   1   1   1   1   1 ]
cim : [175 175   1   8   1   1   1   1   1   1   1   1   1   1   1   1 ]
traj: [  3  96 120   1   1   1   1   1   1   1   1   1   1   1   1   1 ]

>> size(recoNLINV)
ans = 175   175     1     1     1     1     1     1     1     1    20

>> size(recoNLINVRT)
ans = 175   175     1     1     1     1     1     1     1     1    20

>> size(coilsensNLINV)
ans = 350   350     1     8     1     1     1     1     1     1    20

>> size(coilsensNLINVRT)
ans = 175   175     1     8     1     1     1     1     1     1    20

**Comment by uecker** [comment]
I am aware and this will be changed. Both. direct non-Cartesian support in nlinv and rtnlinv are pretty new in the public BART version, ....

**Comment by MartinK84** [comment]
Thanks for the quick feedback, I will be monitoring the repository for changes!

I have given the nlinv algorithm multiple goes over the recent years (even tried your old MATLAB code from many years ago) and this is the first time that it worked out of the box (or worked at all with custom data). So thank you for the work already invested in this!

**Comment by uecker** [comment]
strange, it should be very close to the matlab version.

**Comment by uecker** [comment]
This should be fixed on master.

**Comment by MartinK84** [comment]
Thank you, everything works now :+1:
