### ISSUE TITLE
Activated CUDA?

### ISSUE THREAD

**Issue by kingaza** [mrirecon/bart#239]
hello,

I build BART successfully with CUDA:
```
CUDA?= 1
CUDA_BASE ?= /usr/local/cuda/
```

Then I run `bart ecalib`. It works, however, I cann't see the process via nvidia-smi.
So I am wandering if bart use CUDA or not.

thx.

**Comment by uecker** [comment]
You need to use the '-g' option to use the GPU.

'bart ecalib -g'

For ecalib, only the some part of the processing then uses the GPU. It may not always lead
to a speed up. It makes more sense for 'pics', which can be a lot faster on the GPU.

'bart pics -g'

Please direct future questions to the mailing list. Github issues are not the right place for this.
