### ISSUE TITLE
error: unknown type name 'uint'

### ISSUE THREAD

**Issue by JosephGWoods** [mrirecon/bart#240]
I pulled the latest version of bart from git today and recompiled on both my CentOS Linux and macOS systems. It compiled fine on the Linux system, but failed on my mac due to the following error:

/Users/jwoods/Documents/MATLAB/bart/src/num/ops.c:728:7: error: unknown type name 'uint'
  for (uint i = 0; i < D + 1; i++)
       ^~~~

I fixed this by simply changing "uint" to "unsigned int".

I'm using the gcc-mp-6 compiler and haven't had this issue before. Just thought I'd let you know!

**Comment by jtamir** [comment]
I get the same error. Looks like uint is only defined in GLIBC: https://stackoverflow.com/questions/43892984/gcc-5-6-and-7-on-osx-do-not-support-uint

**Comment by JosephGWoods** [comment]
unit has been used again in src/num/mdfft.c in static int next_powerof2(uint x)
