### ISSUE TITLE
GPU Version of ESPIRiT Calibration?

### ISSUE THREAD

**Issue by Jinwei1209** [mrirecon/bart#241]
Hi, I use bart command line tools in my reconstruction pipeline. I wonder if there is any GPU implementation of ecalib for faster computation? Thanks.

**Comment by uecker** [comment]
ecalib has an undocumented GPU option (-g) for the second part of the algorithm. You also should look at coil compression, or look at enlive (for calibration). Please ask questions on the mailing list and do not use Github issues next time. This is not an issue.

**Comment by Jinwei1209** [comment]
Thanks for the reply. Will ask the question on the mailing list next time.
