### ISSUE TITLE
Compilation fails when memory CFL enabled

### ISSUE THREAD

**Issue by hakkelt** [mrirecon/bart#253]
To incorporate BART in a quite complex processing pipeline, I intended to develop a module that receives input parameters and files over sockets and then passes them to the needed module's main function.

In-memory CFL files would be really handy in this situation, but I was quite annoyed to realize that BART won't compile when `ENABLE_MEM_CFL` is set to `1` in the makefile. Besides some syntax errors (in `src/misc/io.c` and `src/misc/mmio.c` undefined identifier `MEM` is used instead of enum value `FILE_TYPE_MEM`), some more severe compilation errors occur, e.g:
```
./src/main.h:6:39: error: expected ‘,’ or ‘...’ before ‘argv’
    6 | extern int main_ ## x(int argc, char* argv[argc]);
```
I guess, the problem is that there are some C/C++ incompatibilities (some C header is included in `mmiocc.cc` which is compiled with g++).

Did I miss something, and this feature should work (maybe by changing something else in the makefile), or is it abandoned? As far as I could understand from the code, it was intended to be used by pyBART, an interface that also seems to be "forgotten". Are there any plans to continue the development of these features, or is there an easy way to fix the errors?

**Comment by uecker** [comment]
The compile errors are now fixed. But the code is unmaintained and does not integrate well with the rest of BART (style, language, etc) so I am not sure whether I should keep it around. Do you think POSIX shared memory segments would work for you?

pyBART is in a similar situation. There are people working on new Python integration...

**Comment by hakkelt** [comment]
Thanks for the quick reply and for the solution. Yes, POSIX shared memory is perfectly fine.

**Comment by uecker** [comment]
I added support for shared memory segments. You could use it like this:
bart command /input.shm /output.shm
or similar using the 'bart_command' function when using BART as a library.
The only caveat is that I uncommented the flag needed for BART to create such files if they do not already exist (see the commit). The reason is that I do not want it to be used from scripts to not pollute this shared memory namespace and having left over files which on Linux would end up in /dev/shm/.   So I think software which uses this should create the output files before calling BART and then clean up later. Let me know if this does not work for your purpose.

**Comment by hakkelt** [comment]
Well... Today, I tried out using shared memory segments, but at the end of the day, I came to the conclusion that this also something that likely won't work out for me. Unfortunately, the thing is that my task has quite a few uncomfortable constraints that make it almost impossible to use BART as intended. The most painful ones are the following: The software environment to which I want to integrate BART
- runs on Windows,
- is mainly written in Java,
- aims to avoid writes to the file system whenever possible (for security reasons), and
- as the environment already has a huge number of dependencies, new dependencies (such as WSL and Cygwin) are undesired.

At this point, I can fully accept if you consider this problem a rare corner case, and these constraints are "orthogonal" to the design principles of BART, so you don't invest any more effort to find a solution for this problem. However, my experiences with the problem might be useful, so let me give a short overview:

So far, I managed to compile BART with Cygwin (without GPU support though) and make it independent from the Cygwin environment by copying the necessary DLLs to the same folder where the executable resides. At this point, the file system requirement is the only constraint not satisfied, so that's why I thought that shared memory segments are perfect solutions, but, sadly, it needs Cygwin to be installed along with the [Cygserver](https://cygwin.com/cygwin-ug-net/using-cygserver.html) Windows service.

I've already tried to compile BART as a library and then use JNI (Java Native Interface) to call it from Java natively, but I'm stuck with this direction because the default gcc of Cygwin produces x86 binaries (and the attached Cygwin DLLs make them compatible with x64 architectures) and JNI accepts only x64 binaries. The [MinGW w64 compiler](http://mingw-w64.org/doku.php) is a solution to this problem as it supports x64 systems, but it fails to compile BART (it has some problems with fcntl.h).

Currently, the only feasible way I see to solve my problem is 1) to use [ZeroMQ](https://zeromq.org/) to communicate between BART and the Java program over sockets, 2) write a BART module that receives the data and the parameters, and 3) implement a fallback version for your shm interface that works even in case of stand-alone Windows executables. I think, anonymous files or a simple malloc would be just fine for this task, and a simple dictionary is also needed to map virtual file names to memory addresses (similarly how in-memory cfl was implemented, but I intend to implement it in C). But of course, I would be happy to hear if you have a better idea for this issue.

Anyway, if either you or other members of the development team have the capacity to deal with such problems, I can open a new issue to discuss issues related to Windows compatibility, and I'm also open to contribute to fixing these incompatibilities.

**Comment by uecker** [comment]
We can easily add something like a simple C version of memory cfl  files again if this helps.  Compilation with MinGW also seems doable but would require more work. We have some limited experience with cross compilation from Linux to Windows. While we do not have much experience with Windows in general, there are some people who could look at issues. So please feel free do open issues.

**Comment by hakkelt** [comment]
Now I'm a bit more careful with my statements, but I would say that memory cfl files are suitable for my purposes. :)

**Comment by uecker** [comment]
Ok, take a look. I replaced it with a new C-based implementation. See the unit test for an example: The external code would do the memcfl_* calls.

**Comment by hakkelt** [comment]
Thanks, it works perfectly! However, there one addition I suggest: It would be useful to have a function to register an already allocated memory region (something like `register_mem_cfl_non_managed` in `bart_embed_api.h`). Locally I managed to solve it by changing only a couple of lines in `memcfl.c`:

```c
struct memcfl {

	const char* name;

	int D;
	const long* dims;
	complex float* data;

	int refcount;
	bool managed; // Added this line

	struct memcfl* next;
};

static struct memcfl* memcfl_list = NULL;

// This is the new function that is almost identical to the former memcfl_create
void memcfl_register(const char* name, int D, const long dims[D], complex float* data, bool managed)
{
	PTR_ALLOC(struct memcfl, mem);

	mem->name = strdup(name);
	mem->D = D;
	mem->next = memcfl_list;

	long* ndims = *TYPE_ALLOC(long[D]);

	for (int i = 0; i < D; i++)
		ndims[i] = dims[i];

       // Removed the allocation from here

	mem->dims = ndims;
	mem->data = data;
	mem->refcount = 1;
	mem->managed = managed; // Added this line

	memcfl_list = PTR_PASS(mem);
}

// Moved most of its lines to memcfl_register
complex float* memcfl_create(const char* name, int D, const long dims[D])
{
	complex float* data = xmalloc(io_calc_size(D, dims, sizeof(complex float)));
	memcfl_register(name, D, dims, data, true);
	return data;
}

[...] // memcfl_load and memcfl_unmap are unchanged

void memcfl_unlink(const char* name)
{
	struct memcfl** mem = &memcfl_list;

	while (NULL != *mem) {

		if (0 == strcmp((*mem)->name, name))
			break;

		mem = &(*mem)->next;
	}

	struct memcfl* o = *mem;

	*mem = (*mem)->next;

	// for regular files this is not a problem

	if (0 < o->refcount)
		error("Error unlinkin mem cfl\n");

	xfree(o->name);
	xfree(o->dims);
	if (o->managed) // Added this line
		xfree(o->data);
	xfree(o);
}
```

**Comment by uecker** [comment]
Looks good! Would you mind creating a pull request?

**Comment by hakkelt** [comment]
Sure, gladly. #255
