### ISSUE TITLE
BART as shared library?

### ISSUE THREAD

**Issue by hakkelt** [mrirecon/bart#267]
For the project I'm currently working on, I've written a [Java wrapper](https://github.com/hakkelt/bartWrapper) that runs smoothly on Windows accessing functions via native calls from a DLL compiled from BART.

My question is rather strategical in nature: Are you interested in incorporating the C part of the Java wrapper into this repo (it would mean a C header and a source file plus a couple of extra lines in the makefile) or is it better to keep it separately? Also, are there any plans to make BART accessible as a shared library?

@uecker mentioned in #253 that some people are working on a new Python integration. Can I ask what kind of approach they are following? Is it a "shared library"-based approach or the current "system call"-based approach remains? I'm asking this because the "shared library" solution looks cleaner for me from the user's perspective, especially if the Java/Python/Julia wrapper would be published to the central package repositories of these languages with precompiled binaries... And the same approach I use in the Java wrapper would be analogously applicable for a Python or a Julia wrapper.

For instance, I prefer to prototyping in Julia on my Linux machine or a Linux server, but later I need to develop on Windows + Java. Keeping the BART version consistent on all machines and systems tends to be cumbersome in the long run with the current solution.

**Comment by uecker** [comment]
This depends on whether we would be able to maintain this or not. Previously we had to remove similar thing because they broke and nobody fixed it. But if  it comes with a simple test that can be run on Linux automatically with standard dependencies, then I think we can try. 
Compiling BART as a shared library is simple on Linux, should we add a Makefile target?
UCB is working on languages wrappers using SWIG.

**Comment by hakkelt** [comment]
I fully understand that maintainability is the most important question in this topic. I've written simple tests for my Java wrapper, and only [Maven](https://maven.apache.org/) needs to be installed along with Java to download the required java packages and then compile and run the tests. Do Java and Maven count as standard dependencies?

I'll check out how easy it is to rewrite the wrapper with SWIG. I think it would complicate a bit the code, but it might improve the maintainability and it would definitely open up the way to Python and other languages, so it's definitely worth trying.

> Compiling BART as a shared library is simple on Linux, should we add a Makefile target?

Yes, it would significantly simplify the compilation process.

**Comment by malits** [comment]
Hi @hakkelt, I've been working for a little while on Python wrappers. I've been working on wrappers using SWIG (for internal functions) and a syscall-based approach (for exposing command-line tools to a Python interface). I'll update my repo at github.com/malits/bart-swig shortly with current code but would be happy to sync up with you and discuss code similarities and further directions.

**Comment by hakkelt** [comment]
Hi @malits, your wrapper looks really nice! It would be really interesting to combine your SWIG wrapper with the shared library approach. In fact, I wished to implement something like this when I started my Java wrapper, but so far I didn't have enough time to create a proper interface to the internal functions. So I would be glad to discuss the ways we can join our forces to create nice wrappers.

**Comment by uecker** [comment]
I added the Makefile target shared-lib for building shared libraries last year. If you need something else, please let us know.
