### ISSUE TITLE
Assertion `1 == ksp_dims[MAPS_DIM]' failed

### ISSUE THREAD

**Issue by duancaohui** [mrirecon/bart#268]
`bart pics -l1 -r0.001 file_ks file_sensemap image_out`
```
bart: src/pics.c:230: main_pics: Assertion `1 == ksp_dims[MAPS_DIM]' failed.
Aborted (core dumped)
```

**file_ks**: size = (1, 8, 256, 320, 4), 8 is the number of coils, 4 is the slices

**file_sensemap**: size = (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 8, 256, 320, 4)

**Comment by sidward** [comment]
Hello,

In BART, the locations of the dims are important. Please reshape both arrays to (256, 320, 4, 8, 1)

**Comment by uecker** [comment]
Please refer to the mailing list for help.
