### ISSUE TITLE
Cartesian undersampling for 2D

### ISSUE THREAD

**Issue by Jerzy97** [mrirecon/bart#293]
Hi,

I'm an absolute Bart newbie.

I was wondering, whether it is possible with Bart to create 2D cartesian undersampling patterns.
What I mean by that are masks, e.g. like those in Figure 5 in this paper: https://arxiv.org/abs/1811.08839
I am only aware of the tools: poisson & traj. Both seem to have a different purpose.

Could you explain either: How to create such masks or if there is a reason (other than time) why it is not implemented, if not?

Thanks a lot in advance,
Georg

PS:
Also, Idon't know whether this is the most appropriate place to ask such questions. Hint for other ways of asking questions are appreciated as well.

**Comment by hcmh** [comment]
Hi Georg,

such questions are better placed on the mailing list:

https://lists.eecs.berkeley.edu/sympa/info/mrirecon

as a question is not an issue with bart. 

As to your question: for regular Cartesian undersampling, there is `upat`. However, in the paper you linked, they are using random Cartesian undersampling in 1D. For this, I think the only way to do it with bart tools is using poisson with `bart poisson -Z1` (so, setting one of the dimensions to 1), and then adding a calibration region by hand. 

If you want more specific answers, please use the mailing list.

Best regards,
Christian
