### ISSUE TITLE
library build errors with RHEL7: Field 'name' not cached

### ISSUE THREAD

**Issue by lemaiw** [mrirecon/bart#299]
Hello,

I'm currently running into a similar issue as #249  compiling BART 0.8.00 on RHEL7 but with GCC 12.1.0. I don't have sudo/root on the machine I'm curious if there is a work around or precompiled binaries for RHEL7 that are available for download instead of via package manager.

Thank you in advance and happy new year.

**Comment by hcmh** [comment]
> There are packages for CentOS 7 here, please test. https://copr.fedorainfracloud.org/coprs/schaten/bart/

Hi [lemaiw](https://github.com/lemaiw) ,

in the issue you linked, Martin Uecker linked packages including EPEL7. I am not too familiar with RHEL, but a google search told me that those packages should work for you. Could you give them a try?

**Comment by lemaiw** [comment]
Hi Christian,

Thank you so much for your swift reply. I took a look at this link in the
older issue and it appeared from the instructions that sudo and yum/dnf
would be required for the install and I do not have those privileges on the
machine I'm attempting to build. I hope you'll pardon this question if it's
dense but I'm unfamiliar with copr fedorainfracloud and a cursory google
search did not give me much as to how to download this package from there
without a package manager. I might be looking in the wrong place? Once
again, apologies if this is dense.

Best,
Le Mai

**Comment by uecker** [comment]
We have new tests and updated README for installing on different Linux machines.. Please reopen if necessary.
