### ISSUE TITLE
Issues with making bart v 0.8.00

### ISSUE THREAD

**Issue by pasalacquaian** [mrirecon/bart#302]
I thought it would be an easier installation this time since I am now using WSL instead of Windows, but there still seems to be many issues. For reference, I am using WSL2 with Ubuntu 22.04.02

I followed the commands verbatim on this page: https://mrirecon.github.io/bart/installation.html. I have been trying to install v0.8.00

The issues began when I got around to the make command. 

Error #1:  
![image](https://user-images.githubusercontent.com/59702377/225095939-5b9076aa-f874-4b2e-8cc3-253e2f6a05fa.png)
Seems that the bart file can't find fftw3.h. I looked around and, well, I couldn't find it anywhere either. So I commented out that line in the bart file and tried again.

Error #2: Lots of warnings showed up about some inconsistencies in the code, and then I got this:
![image](https://user-images.githubusercontent.com/59702377/225096923-42eeba1f-e01b-4718-a9f5-c7f92a0cf195.png)
I wasn't able to find this either when I looked around. I figured since I was this far, let's not include cblas.h in the blas file

Error #3: A long list of errors regarding no cblas came about that I assume are due to my removal of the line that led to error #2.

I've run out of ideas to make this installation work, and I don't know where the issue stems from. This has been an incredibly difficult package to make!

**Comment by pasalacquaian** [comment]
Hi Jon,

That seems to have worked! Is there any way these instructions could be made public or more easily found? They don't appear in the README file or elsewhere on the site from what I can tell.

**Comment by jtamir** [comment]
Yes we are in the process of updating it. Apologies that it wasn’t more clear.

Sincerely

Jon
www.jtsense.com
________________________________

**Comment by uecker** [comment]
I wonder why the original instructions did not work? They include the commands for installing fftw3 and blas. Was there an error before?  For Ubuntu there is also a pre-compiled package distributed with Ubuntu you can just install.

**Comment by pasalacquaian** [comment]
I'm not sure...when I installed fftw3 and blas, some warnings came up, but it didn't appear to be anything serious. Unfortunately, I don't remember what the warnings were, and can't seem to recreate them on my current device. I didn't notice the pre-compiled package-- I'll try it out if I need to install bart on another Linux system!
