### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [mrirecon/bart#309]
/src/nn/nn.c line 227
Code:
static int get_index_from_name(int N, const char* names[N], const char* name)
{
	for (int i = 0; i < N; i++)
		if ((names[i] != NULL) && (names[i] != NULL) && ((0 == strcmp(name, names[i])))) // <-- identical (names[i] != NULL) 
			return i;
	return -1;
}

**Comment by maddin200** [comment]
may be
f ((name != NULL) && (names[i] != NULL) && ((0 == strcmp(name, names[i]))))

**Comment by uecker** [comment]
Done. Thanks!
