### ISSUE TITLE
CFL file error

### ISSUE THREAD

**Issue by jaykumar16** [mrirecon/bart#314]
Hi, 

WARN: file: Opening file which was not previously reserved for in- or output!
ERROR: private cfl file

This is the error I am getting using Bart Version 8. 
The reconstruction is performed over a storage system mounted via sshfs.  All of the output files result in this error. 

Please help.

**Comment by uecker** [comment]
Please use the mailing list for questions: https://mrirecon.github.io/bart/

Also you need to provide more information, e.g. see Reporting Problems in the README.  For your question: Does this problem only occur when using sshfs or also on the local file system?
