### ISSUE TITLE
make error: fatal error: lapacke.h:

### ISSUE THREAD

**Issue by ryao-mdanderson** [mrirecon/bart#330]
Dear Bart developer:
 
I am an HPC system administrator for the institute research cluster. I am assisting a scientist to set up bart on our system, a RHEL 8.7 cluster.
 
I did the following steps:
 
1, git clone https://github.com/mrirecon/bart
 
2,Per README, our system has met the requirements,
 
Required in README: “To install the required libraries on Redhat / Centos run:
  $ sudo yum install atlas-devel fftw3-devel libpng-devel lapack-devel”
 
On our system, the packages are installed to meet the requirement:
$ rpm -qa | grep atlas
atlas-3.10.3-8.el8.x86_64
atlas-devel-3.10.3-8.el8.x86_64
 
$ rpm -qa | grep lapack-devel
lapack-devel-3.8.0-8.el8.x86_64
 
$ rpm -qa | grep fftw
fftw-libs-single-3.3.5-11.el8.x86_64
fftw-libs-quad-3.3.5-11.el8.x86_64
fftw-devel-3.3.5-11.el8.x86_64
fftw-libs-3.3.5-11.el8.x86_64
fftw-libs-double-3.3.5-11.el8.x86_64
fftw2-2.1.5-40.el8.x86_64
fftw-static-3.3.5-11.el8.x86_64
fftw-libs-long-3.3.5-11.el8.x86_64
fftw-3.3.5-11.el8.x86_64
 
$ rpm -qa | grep libpng
libpng15-1.5.30-7.el8.x86_64
libpng-1.6.34-5.el8.x86_64
libpng-devel-1.6.34-5.el8.x86_64
 
“The minimum GCC supported is 11.”
We use gcc version 11.3.0
 
However, the ‘make’ command hit an error:
$ cd /tmp/bart/
$ make
…
/tmp/bart/src/num/lapack.c:21:10: fatal error: lapacke.h: No such file or directory
   21 | #include <lapacke.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:824: /tmp/bart/src/num/lapack.o] Error 1
 
I located lapacka.h on the system
$ locate lapacke.h
/usr/include/lapacke/lapacke.h
/usr/include/openblas/lapacke.h
/usr/share/man/man3/lapacke.h.3.gz
 
Please advise if I overlooked anything. Thank you very much for your help,
Rong Yao

**Comment by ryao-mdanderson** [comment]
Hello Martin,

Thank you! I just find your reply in my email box. Appreciate!  I have follow up questions in my reply.

Best,
Rong

**Comment by tashrifbillah** [comment]
Hi @uecker, I did:

```
make allclean
NOLAPACKE=1 make
```

But still got:

```
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:792: bart] Error 1
```

I am using v0.9.00. Any help?

**Comment by tashrifbillah** [comment]
Isn't the purpose of `NOLAPACKE` to disable it? Why did you put `MODULES += -llapacke` in this block?

https://github.com/mrirecon/bart/blob/afd1bf75a44062b0b88fd9385e1986e0ad6fbb91/Makefile#L388-L391
