### ISSUE TITLE
Questions: In SCC coil compression, why eigen decomposition of covariance instead of SVD ?

### ISSUE THREAD

**Issue by fzimmermann89** [mrirecon/bart#331]
Hi,

maybe I am missing something, but while checking what exactly bart does for scc coil compression, I noticed you are doing the pca via eigendecomposition. Often, SVD of X is said to be more stable than Eigendecomposition of XtX. Is there a particular reasoning behind this decision?

https://github.com/mrirecon/bart/blob/aa78cc847651dda3884d29060caa6f32ad9e55ae/src/calib/cc.c#L55-L58

Thanks!
-Felix

**Comment by uecker** [comment]
The is no real  reason. The answer is/that it is  slightly simpler to implement and I would be surprised if it matters for the noise levels we have in MRI. Also not that this is does not implement a PCA as the mean is preserved. Please use the mailing list for future discussions.
