### ISSUE TITLE
twixread cannot read Siemens data - Input/output error

### ISSUE THREAD

**Issue by VasudevDevulapally** [mrirecon/bart#339]
Dear all,

I am trying to Siemens data file and i an incurring input/output error when i use twixread for reading .dat files for siemens. Kindly let me know the reason for this error

>  bart twixread -A meas_MID00080_FID04407_XTE_gmPETRA_TE-0.01.dat /mnt/nicshare/Skull_Imaging_VD/VD_Skull_Imaging_Test/Acquisition_files/July/raw_data_July_22_2024/
> V[D Header. MeasID: 80 FileID: 4407 Scans: 2
> Patient: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Protocol: XTE_gmPETRA_TE-0.01
> VD Header. MeasID: 80 FileID: 4407 Scans: 2
> Patient: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Protocol: XTE_gmPETRA_TE-0.01
> WARN: Wrong number of samples: 1 != 0.
> WARN: Stopping.](url)

> bart twixread -A meas_MID00077_FID04404_AdjCoilSens.dat /mnt/nicshare//Skull_Imaging_VD/VD_Skull_Imaging_Test/Acquisition_files/July/raw_data_July_22_2024/
> VD Header. MeasID: 77 FileID: 4404 Scans: 1
> Patient: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Protocol: AdjCoilSens
> VD Header. MeasID: 77 FileID: 4404 Scans: 1
> Patient: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Protocol: AdjCoilSens
> shared cfl /mnt/nicshare /Skull_Imaging_VD/VD_Skull_Imaging_Test/Acquisition_files/July/raw_data_July_22_2024/.cfl : Input/output error](url)

**Comment by uecker** [comment]
Please do not use the issue tracker for help.  There is a mailing list. 

It seems though you provide an output directly, but you not to specify an output file.  The error message might also indicate that the automatic mode does not understand your data. In this case it may help to specify the dimensions manually. Alternatively, there is matlab code you can find on the internet which may help reading your data (mapVBVD.m).
