### ISSUE TITLE
bart copy does not behave like expected

### ISSUE THREAD

**Issue by dabosch** [mrirecon/bart#341]
Hi,

the help of bart copy (`bart copy -h`) tells me what it supposedly does:
> Copy an array (to a given position in the output file - which then must exist). 

From this I assume that data from array a is copied into a position of array b, overwriting what's already in those positions, and implicitely not modifying the rest of array b.
However, when I use it, array b is actually completely cleared, and only the data from array b is still there. So either the description is unclear, or the behavior is not as intended.

I added a demo below.

Best,
Dario

## Demo:
```bash
# generate a phantom
bart phantom -x128 phantom
bart toimg phantom phantom.png
```
![phantom](https://github.com/user-attachments/assets/f0b46338-712e-49e8-b29d-a3c379dfc100)

```bash
#now extract the 2nd half of the phantom and scale it with factor 1.2 (make it a bit brighter)
bart extract 1 64 128 phantom phantom_right
bart scale 1.2 phantom_right phantom_right
bart toimg phantom_right phantom_right.png

```
![phantom_right](https://github.com/user-attachments/assets/c942d413-bb8d-4700-be9d-c2f3934f211d)

```bash
# copy the scaled portion back into a copy of the original array
cp phantom.cfl phantom_copied.cfl
cp phantom.hdr phantom_copied.hdr
bart copy 1 64 phantom_right phantom_copied
bart toimg phantom_copied phantom_copied.png
```
![phantom_new](https://github.com/user-attachments/assets/d3c622ea-bb1a-430b-99df-f6b66960b6a4)

I would expect the image to be a complete phantom, with the right half to be a bit brighter than the left half. Instead, the left half is completely lost.
For the intended result, I have to also extract the other portion of the data and stitch it together:
```bash
# join left and right half
bart extract 1 0 64 phantom phantom_left
bart toimg phantom_left phantom_left.png
bart join 1 phantom_left phantom_right phantom_joined  
bart toimg phantom_joined phantom_joined.png
```
![phantom_joined](https://github.com/user-attachments/assets/e980eeb2-0b02-4508-b153-249faf4fce62)

**Comment by mblum94** [comment]
Thank you for reporting this bug. We fixed it and will commit the update soon.
