### ISSUE TITLE
bart-0.9.00/src/num/fft.c:529: fft_apply: Assertion `NULL != plan->fftw' failed.

### ISSUE THREAD

**Issue by tsaiweiwu** [mrirecon/bart#346]
I am running bart in matlab with these commands below 

temp = rand(1, 128, 128, 24);
sense = squeeze(bart('ecalib -S -t0.01 -m1', temp));

I received 

bart-0.9.00/src/num/fft.c:529: fft_apply: Assertion `NULL != plan->fftw' failed.
bart-0.9.00/bart ecalib -S -t0.01 -m1  /tmp/tp4404cbd2_7e2c_427d_a69f_8311a57121a5in1  /tmp/tp4404cbd2_7e2c_427d_a69f_8311a57121a5out1: Aborted

Is this due to memory issue? How can I get around this?

**Comment by mblum94** [comment]
Hi,

unfortunately, I cannot reproduce this behaviour.

In bash I tried:

bart version
bart zeros 4 1 128 128 24 z
bart noise z n
bart ecalib -S -t0.01 -m1 n c

working well ( printed version is v0.9.00)
Could you try to reproduce this?

**Comment by tsaiweiwu** [comment]
Thanks for your reply. 

I just found out that passing -Wl,-rpath into FFTW_L in the Makefile solves my problem.

I used gcc/9.3.0 openmpi/3.1.6 and MKL for BLAS
Here is my make argument

make \
PREFIX=$PREFIX \
SHARED=0 SCALAPACK=0 \
FFTWTHREADS=0 \
MKL_BASE=$MKLROOT \
FFTW_BASE=$FFTW_HOME \
MATLAB_BASE=$MATLAB_HOME \
MPI=1 OPENBLAS=0 MKL=1 PARALLEL=1 PNG=1 

I found out that I have to use RPATH for FFTW_L as below and that solved my issue. 

FFTW_L := -Wl,-rpath $(FFTW_BASE)/lib -L$(FFTW_BASE)/lib -lfftw3f 

I don't really understand why -Wl,-rpath is necessary here. Any explanation would be appreciated.

**Comment by mblum94** [comment]
Not sure, but I had similar issues on a HPC cluster, where multiple versions of a library were available. The corresponding library pathes were not set on the compute node.

So we set the rpath option as default after release of v0.9.00: commit 0793a96
