### ISSUE TITLE
Can't compile with CUDA alone on Mac OS X

### ISSUE THREAD

**Issue by davidssmith** [mrirecon/bart#4]
Mac OS X Yosemite uses Clang, which doesn't support OpenMP.

You can install separately GCC, which supports OpenMP, but GCC is not compatible with `nvcc` on Yosemite.

`¯\_(ツ)_/¯`

So CUDA compilation works on OS X, but some of the GPU source assumes the presence of OpenMP, so the make dies on `src/num/gpuops.c`.

Would it be possible to unravel the CUDA and OpenMP dependencies so that CUDA does not require OpenMP?

Great package, by the way.  I hope to contribute some of my code to it at some point. Just have to plug it into the mmio concept.

**Comment by frankong** [comment]
For the time being, you can try CUDA 6.0. It’s compatible with GCC on Mac and it should work as some of us use Yosemite with CUDA and openmp on. Nvidia only decides not to support GCC on Mac in CUDA 7.0 for some reason.



-Frank

**Comment by davidssmith** [comment]
Thanks, I'll try that.
