### ISSUE TITLE
Cuda out of memory error for ecalib and pics

### ISSUE THREAD

**Issue by chrisranderson** [mrirecon/bart#45]
I'm new to this MRI business, so I may be doing something totally crazy. Here is my code (part of it, anyway):

```python
kspace = cfl.readcfl('data/{}'.format(filename))
sensitivities = bart(1, 'ecalib -g', kspace)
```

I get this error:

```python
CUDA Pointwise Eigendecomposition...
ERROR: Error: ERROR: cuda error: 230 out of memory 
Aborted (core dumped)
Traceback (most recent call last):
  File "sandbox.py", line 32, in <module>
    sensitivities = bart(1, 'ecalib -g', kspace)
  File "/home/chris/bart/python/bart.py", line 61, in bart
    raise Exception("Command exited with an error.")
```

The file is a 1 GB .cfl file (and the kspace array is just over 1 GB in memory). Is that too big? Here are my GPU specs:
![image](https://cloud.githubusercontent.com/assets/5461398/15839254/a265ab52-2bff-11e6-90c0-a53a5d7dc89b.png)

It worked great without using the GPU. `pics` also works fine without the GPU, but dies with the same error.

The shape of `kspace` is `(320, 288, 236, 6)`. I'm not sure what the last dimension is; can I somehow slim down the 4th dimension from 6 to 1 to help things fit? Maybe I'm going down the wrong road.

edit: I got my .cfl from here (the first entry): http://mridata.org/undersampled/knees 
2nd edit: I tried using kspace[:,:,:100,:], but I get an error as well:

```python
ERROR: invalid argument
Aborted (core dumped)
Traceback (most recent call last):
  File "sandbox.py", line 32, in <module>
    sensitivities = bart(1, 'ecalib -g', kspace)
  File "/home/chris/bart/python/bart.py", line 61, in bart
    raise Exception("Command exited with an error.")
Exception: Command exited with an error.
```

**Comment by siatjiasen** [comment]
Hi,

I got same out of memory error previously. Dr. Martin Uecker told me to try 'rsense' . Currently, 'rsense' comes with limited regularization options, thus my solution is:
1. perform 1D ifft along Readout dimensions.
2. using gpu pics to recon 288x236x6 data (repeat 320 times).

The last dimensions 6 is channel dimension for parallel imaging, that is using 6 receivers of different sensitivities to do sampling. Thus you can't slim down the 4th dimension from 6 to 1.

Best wishes,

**Comment by jtamir** [comment]
I haven't tested the GPU implementation of ecalib, so I can't comment on it.

As @siatjiasen said, you are running out of memory. If you are just interested in seeing if it's possible to run on the GPU, you could try to coil-compress the data to a smaller number of channels first using the `bart cc` command. But you will probably lose some accuracy.

If you want to go the slice-by-slice route and require more advanced options than are currently available through `bart rsense`, you can call `bart pics` in a loop. I suggest using the [Grasp script](https://github.com/mrirecon/bart/blob/master/scripts/grasp.sh) as a reference.

In the future we will probably merge `rsense` and `pics`.
