### ISSUE TITLE
Matlab memory / write-read speed

### ISSUE THREAD

**Issue by timlod** [mrirecon/bart#46]
Hey, 
First off, thanks for BART - I am getting into using the toolbox and so far really like the results!

I am interfacing with Matlab and noticed that readcfl always returns doubles and was wondering if that is intentional (as BART seems to be outputting only single precision values). We are working with very large datasets and therefore memory usage must be kept down.

Right now readcfl.m reads float32s and converts them to double. Then it instantiates a double (non-complex) array which will be immediately reallocated as a complex matrix to fit the complex doubles.
writecfl.m also instantiates an extra double array for the values (where in my case then all the single data first needs to be promoted to double).

I modified both methods and saw speed increase significantly. Memory usage halves due to keeping the values as singles.
Should I make a pull request about this?
Best, Tim

**Comment by uecker** [comment]
Yes, thank you. I am sure our Matlab user will appreciate this! Please follow the procedure "Information for Contributors".

**Comment by timlod** [comment]
Alright! See #47

**Comment by uecker** [comment]
Thank you.
