### ISSUE TITLE
Question: pre-kspace time series data?

### ISSUE THREAD

**Issue by chrisranderson** [mrirecon/bart#49]
I'm looking for data straight off the receive coil (or whatever the most raw, original data is), before it is processed/transformed to kspace. Do you know of any datasets like that? Also, does your tool handle any of that type of processing?

Thanks!

**Comment by uecker** [comment]
I am not sure what you are trying to achieve. k-space data is already very close to what you get from the receivers. The only processing done before should be demodulation, which I think is done by software on a DSP for all modern MRI scanners. But I do not know how whether is is even possible to get this data somehow from a typical MRI scanner.

Also please use the mailing list for discussion and questions. Issues are for bugs or problem with the software.
