### ISSUE TITLE
Joint wavelet regularization not supported in pics

### ISSUE THREAD

**Issue by jtamir** [mrirecon/bart#54]
Currently not implemented. Requires using `prox_unithresh_create` along with a wavelet linop

**Comment by uecker** [comment]
See my attemp for wavelet3 in joint-wavelet2 ... completely untested but I think it should work...

**Comment by jtamir** [comment]
Is your wavelet3 competitive in speed with wavelet2 on CPU and GPU?

If not I still prefer to have the special case of wavelet2 + unitary
threshold for 3D, since I use it in a clinical setting. If it is then we
should get rid of wavelet2 completely.

Jon

**Comment by uecker** [comment]
No, for the CPU it depends on circumstances and the GPU case is slow. Otherwise I would have removed the wavelet2 code a long time ago...

**Comment by uecker** [comment]
Actually, I did some tests and it seems fast even on the GPU. Maybe because newer ones have a cache and do not rely as much on the explicit use of the shared memory. Are you OK with removing wavelet2?

**Comment by jtamir** [comment]
I will check when I have a chance. @frank thoughts?

**Comment by frankong** [comment]
I'm ok if it's faster. Wavelet2 has served its time

**Comment by jtamir** [comment]
What's the latest on this? I rebased the wavelet branch. Do we have any performance regression tests?

**Comment by uecker** [comment]
Not sure what branch you are talking about...

the old wavelets are not used by default anymore. My plan is to make another release soon, and if nobody complaints too loudly, remove wavelet2 in the release after this. 

For joint thresholding, somebody needs to test whether joint wavelet thresholding in the joint-wavelets2 branch works as intended and contribute a test. Then we could merge that feature.

**Comment by jtamir** [comment]
Okay, I will take a look. That's the branch I'm talking about

**Comment by uecker** [comment]
Implemented on master. Still needs testing
