### ISSUE TITLE
OpenMP causes Clang to Crash

### ISSUE THREAD

**Issue by slacka** [mrirecon/bart#72]
I filed [a clang/LLVM bug report for this issue here.](https://llvm.org/bugs/show_bug.cgi?id=30683)

Please share any helpful information you may have with the clang developers.

**Comment by slacka** [comment]
The clang developer,  Alexey Bataev, fixed this bug with r286129.

**Comment by uecker** [comment]
Great. We had lots of problems with clang and OpenMP in the past, so while it compiles I would still not trust it...

**Comment by slacka** [comment]
Clang developers are very friendly. Please report any bugs if you find them.

**Comment by uecker** [comment]
make test

It actually seems to work fine with clang now (after fixing some problems on our side).

**Comment by uecker** [comment]
hi slacka,

clang problems with openmp reappeared. Maybe you are interested in filing a bug with clang? Otherwise I will do it, but I am travelling and will not have much time in the next weeks. 

See: https://travis-ci.org/mrirecon/bart/jobs/275789592

Martin

**Comment by slacka** [comment]
uecker,
The bug was fixed in clang 4.0.  travis is still using clang 3.9.
