### ISSUE TITLE
Rename CC

### ISSUE THREAD

**Issue by blakedewey** [mrirecon/bart#78]
Is it possible to rename the `cc` binary? If I install it in my PATH, it over shadows the soft link to my C compiler (which CMake looks for).

**Comment by uecker** [comment]
Possibly, but what is wrong with installing the 'bart' master-command, i.e. 'bart cc ...'

**Comment by blakedewey** [comment]
Could we make that the default for installation? The default `make install` installs all commands.

**Comment by uecker** [comment]
The default Makefile doesn't install all commands, or am I missing something? Did you use cmake instead? This was contributed by @hjmjohnson. Somebody would have to provide a patch with the necessary changes (also automatic build testing for cmake would be nice)

**Comment by blakedewey** [comment]
Sorry, yes this was a CMake build (I develop on a Mac). I'll try to sort out changing the default CMake install. Good excuse to learn how it works!

**Comment by uecker** [comment]
Closing as this is a problem with an unsupported build method.
